login: &login
  adapter:  mysql
  username: posters
  password: posters
  host:     localhost
  timeout:  5000
  charset:  latin1

development:
  <<: *login
  database: posters_development

test:
  <<: *login
  database: posters_test

production:
  <<: *login
  database: posters_production